### ISSUE TITLE
Support for including multiple sequences in genbank files

### ISSUE THREAD

**Issue by Aurorabili** [gamcil/clinker#113]
Normally NCBI will merge multiple selected sequences into one `sequence.gb`, it would be great if clinker could handle it automatically.

If this is a good idea I can open a PR for this.

**Comment by gamcil** [comment]
clinker currently reads multi-record GenBank files as multiple loci from the same cluster (e.g. when a cluster is broken over multiple contigs) - I think an optional flag where records are parsed as separate clusters instead could be a good idea. Would very much appreciate a PR for that.

**Comment by gamcil** [comment]
Thanks for the PR, have merged and made a new release so will close this now.
