### ISSUE TITLE
error

### ISSUE THREAD

**Issue by davidmadariaga** [gamcil/clinker#117]
Hi!, hope ur doing great. I'm trying to obtain a comparison between some .gbk sequences of filamentous prophages but got this error. Could you please give me a hand?, this is what i got in the terminal:

(clinker) d@d:~/Documents/Investigaciones/paper2IMSAR/phages$ clinker *.gbk
[01:03:26] INFO - Starting clinker
[01:03:26] INFO - Parsing files:
[01:03:26] INFO -   CTX.gbk
[01:03:26] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[01:03:26] INFO -   m13.gbk
[01:03:27] WARNING - NC_003287.2 is circular, checking for genes spanning the origin
[01:03:27] WARNING - To disable this behaviour, use --dont_set_origin
[01:03:27] INFO - Found 2 features wrapping origin
Traceback (most recent call last):
  File "/home/d/anaconda3/envs/clinker/bin/clinker", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/d/anaconda3/envs/clinker/lib/python3.12/site-packages/clinker/main.py", line 366, in main
    clinker(
  File "/home/d/anaconda3/envs/clinker/lib/python3.12/site-packages/clinker/main.py", line 168, in clinker
    clusters = parse_files(
               ^^^^^^^^^^^^
  File "/home/d/anaconda3/envs/clinker/lib/python3.12/site-packages/clinker/classes.py", line 359, in parse_files
    cluster = cluster_from_genbank(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/d/anaconda3/envs/clinker/lib/python3.12/site-packages/clinker/classes.py", line 304, in cluster_from_genbank
    locus = Locus.from_seqrecord(record, set_origin=set_origin)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d/anaconda3/envs/clinker/lib/python3.12/site-packages/clinker/classes.py", line 528, in from_seqrecord
    record = shift_origin(record)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/d/anaconda3/envs/clinker/lib/python3.12/site-packages/clinker/classes.py", line 70, in shift_origin
    LOG.info(f"Setting new origin to {shift} (start of {feature.qualifiers.get('locus_tag')[0]})")
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by gamcil** [comment]
Is it possible to upload your input files here so I can look? Potentially try using `--dont_set_origin` also, in case this might be buggy.

**Comment by davidmadariaga** [comment]
Thanks for the answer, i compressed the gbk files, here you have
[phages.zip](https://github.com/user-attachments/files/17896282/phages.zip)

**Comment by gamcil** [comment]
Should now be fixed in `clinker v0.0.31`.

**Comment by davidmadariaga** [comment]
THANK YOU VERY MUCH. Is it possible for you to add this phage to the comparisson? if you dont have the time for it dont worry, i'll try by myself. THANK YOU 
[IMSAR-11_1copy.zip](https://github.com/user-attachments/files/17896737/IMSAR-11_1copy.zip)

**Comment by davidmadariaga** [comment]
wait i tried and got this:

(clinker) d@d:~/Documents/Investigaciones/paper2IMSAR/phages$ clinker --dont_set_origin -i 0.2 --plot *.gbk
[00:40:55] INFO - Starting clinker
[00:40:55] INFO - Parsing files:
[00:40:55] INFO -   m13.gbk
[00:40:55] INFO -   mda.gbk
[00:40:55] INFO -   Ngo6.gbk
/home/d/anaconda3/envs/clinker/lib/python3.12/site-packages/Bio/Seq.py:2879: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
[00:40:55] INFO -   pf1.gbk
[00:40:55] INFO - Starting cluster alignments
[00:40:55] INFO - m13 vs mda
[00:40:55] INFO - m13 vs Ngo6
[00:40:55] INFO - m13 vs pf1
[00:40:55] INFO - mda vs Ngo6
[00:40:55] INFO - mda vs pf1
[00:40:55] INFO - Ngo6 vs pf1
[00:40:55] INFO - Generating results summary...
m13 vs mda
----------
Query        Target          Identity  Similarity
NP_510890.1  WP_002218477.1  0.21      0.29      
NP_510890.1  WP_002223585.1  0.24      0.43      
NP_510890.1  WP_002216892.1  0.20      0.37      
NP_510892.1  WP_002223586.1  0.21      0.34      
NP_510892.1  WP_002216892.1  0.21      0.41      

m13 vs Ngo6
-----------
Query        Target      Identity  Similarity
NP_510886.1  AAW89808.2  0.20      0.32      
NP_510886.1  AAW89809.1  0.21      0.27      
NP_510890.1  AAW89810.1  0.23      0.47      
NP_510890.1  AAW89815.1  0.20      0.38      
NP_510892.1  AAW89806.1  0.29      0.39      
NP_510892.1  AAW89812.1  0.21      0.34      

m13 vs pf1
----------
Query        Target       Identity  Similarity
NP_510887.1  NP_039602.1  0.23      0.39      
NP_510887.1  NP_039610.1  0.22      0.36      
NP_510887.1  NP_039613.1  0.21      0.30      
NP_510890.1  NP_039603.1  0.21      0.44      
NP_510891.1  NP_039604.1  0.21      0.28      
NP_510892.1  NP_039608.1  0.20      0.31      

mda vs Ngo6
-----------
Query           Target      Identity  Similarity
WP_002223582.1  AAW89813.2  0.46      0.61      
WP_002218477.1  AAW89810.1  0.21      0.29      
WP_002218477.1  AAW89812.1  0.62      0.74      
WP_002218476.1  AAW89809.1  0.20      0.34      
WP_002218476.1  AAW89811.1  0.58      0.81      
WP_002218476.1  AAW89815.1  0.24      0.33      
WP_002223585.1  AAW89810.1  0.25      0.56      
WP_002223585.1  AAW89815.1  0.23      0.39      
WP_002223586.1  AAW89809.1  0.30      0.47      
WP_002223586.1  AAW89811.1  0.21      0.32      
WP_002223586.1  AAW89812.1  0.22      0.38      
WP_002223586.1  AAW89815.1  0.24      0.35      
WP_042507217.1  AAW89807.1  0.60      0.69      
WP_002216892.1  AAW89806.1  0.34      0.47      
WP_002216892.1  AAW89810.1  0.20      0.37      
WP_002216892.1  AAW89815.1  0.22      0.40      
WP_002212523.1  AAW89805.1  0.37      0.49      
WP_002212521.1  AAW89804.1  0.43      0.59      

mda vs pf1
----------
Query           Target       Identity  Similarity
WP_002218477.1  NP_039603.1  0.21      0.32      
WP_002223585.1  NP_039602.1  0.21      0.28      
WP_002223585.1  NP_039603.1  0.24      0.45      
WP_002216892.1  NP_039602.1  0.22      0.35      
WP_002216892.1  NP_039603.1  0.21      0.40      

Ngo6 vs pf1
-----------
Query       Target       Identity  Similarity
AKO63689.1  NP_039608.1  0.22      0.38      
AAW89806.1  NP_039602.1  0.22      0.38      
AAW89806.1  NP_039605.1  0.22      0.35      
AAW89809.1  NP_039608.1  0.25      0.31      
AAW89809.1  NP_039613.1  0.21      0.29      
AAW89810.1  NP_039602.1  0.22      0.40      
AAW89810.1  NP_039603.1  0.28      0.47      
AAW89812.1  NP_039603.1  0.21      0.27      
AAW89815.1  NP_039602.1  0.24      0.40      
[00:40:55] INFO - Building clustermap.js visualisation
[00:40:55] INFO - Writing to: CTX.gbk
[00:40:55] INFO - Done!

it's saving the output in the CTX.gbk file!, do you know what could be the reason?

i wrote: 

(clinker) d@d:~/Documents/Investigaciones/paper2IMSAR/phages$ clinker --dont_set_origin -i 0.2 --plot *.gbk


thanks in advance and thank you for your time, you already helped me a lot

**Comment by davidmadariaga** [comment]
this is what appeared on the terminal:

(clinker) d@d:~/Documents/Investigaciones/paper2IMSAR/phages$ clinker --dont_set_origin -i 0.2 --plot *.gbk
[00:40:55] INFO - Starting clinker
[00:40:55] INFO - Parsing files:
[00:40:55] INFO -   m13.gbk
[00:40:55] INFO -   mda.gbk
[00:40:55] INFO -   Ngo6.gbk
/home/d/anaconda3/envs/clinker/lib/python3.12/site-packages/Bio/Seq.py:2879: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
[00:40:55] INFO -   pf1.gbk
[00:40:55] INFO - Starting cluster alignments
[00:40:55] INFO - m13 vs mda
[00:40:55] INFO - m13 vs Ngo6
[00:40:55] INFO - m13 vs pf1
[00:40:55] INFO - mda vs Ngo6
[00:40:55] INFO - mda vs pf1
[00:40:55] INFO - Ngo6 vs pf1
[00:40:55] INFO - Generating results summary...
m13 vs mda
----------
Query        Target          Identity  Similarity
NP_510890.1  WP_002218477.1  0.21      0.29      
NP_510890.1  WP_002223585.1  0.24      0.43      
NP_510890.1  WP_002216892.1  0.20      0.37      
NP_510892.1  WP_002223586.1  0.21      0.34      
NP_510892.1  WP_002216892.1  0.21      0.41      

m13 vs Ngo6
-----------
Query        Target      Identity  Similarity
NP_510886.1  AAW89808.2  0.20      0.32      
NP_510886.1  AAW89809.1  0.21      0.27      
NP_510890.1  AAW89810.1  0.23      0.47      
NP_510890.1  AAW89815.1  0.20      0.38      
NP_510892.1  AAW89806.1  0.29      0.39      
NP_510892.1  AAW89812.1  0.21      0.34      

m13 vs pf1
----------
Query        Target       Identity  Similarity
NP_510887.1  NP_039602.1  0.23      0.39      
NP_510887.1  NP_039610.1  0.22      0.36      
NP_510887.1  NP_039613.1  0.21      0.30      
NP_510890.1  NP_039603.1  0.21      0.44      
NP_510891.1  NP_039604.1  0.21      0.28      
NP_510892.1  NP_039608.1  0.20      0.31      

mda vs Ngo6
-----------
Query           Target      Identity  Similarity
WP_002223582.1  AAW89813.2  0.46      0.61      
WP_002218477.1  AAW89810.1  0.21      0.29      
WP_002218477.1  AAW89812.1  0.62      0.74      
WP_002218476.1  AAW89809.1  0.20      0.34      
WP_002218476.1  AAW89811.1  0.58      0.81      
WP_002218476.1  AAW89815.1  0.24      0.33      
WP_002223585.1  AAW89810.1  0.25      0.56      
WP_002223585.1  AAW89815.1  0.23      0.39      
WP_002223586.1  AAW89809.1  0.30      0.47      
WP_002223586.1  AAW89811.1  0.21      0.32      
WP_002223586.1  AAW89812.1  0.22      0.38      
WP_002223586.1  AAW89815.1  0.24      0.35      
WP_042507217.1  AAW89807.1  0.60      0.69      
WP_002216892.1  AAW89806.1  0.34      0.47      
WP_002216892.1  AAW89810.1  0.20      0.37      
WP_002216892.1  AAW89815.1  0.22      0.40      
WP_002212523.1  AAW89805.1  0.37      0.49      
WP_002212521.1  AAW89804.1  0.43      0.59      

mda vs pf1
----------
Query           Target       Identity  Similarity
WP_002218477.1  NP_039603.1  0.21      0.32      
WP_002223585.1  NP_039602.1  0.21      0.28      
WP_002223585.1  NP_039603.1  0.24      0.45      
WP_002216892.1  NP_039602.1  0.22      0.35      
WP_002216892.1  NP_039603.1  0.21      0.40      

Ngo6 vs pf1
-----------
Query       Target       Identity  Similarity
AKO63689.1  NP_039608.1  0.22      0.38      
AAW89806.1  NP_039602.1  0.22      0.38      
AAW89806.1  NP_039605.1  0.22      0.35      
AAW89809.1  NP_039608.1  0.25      0.31      
AAW89809.1  NP_039613.1  0.21      0.29      
AAW89810.1  NP_039602.1  0.22      0.40      
AAW89810.1  NP_039603.1  0.28      0.47      
AAW89812.1  NP_039603.1  0.21      0.27      
AAW89815.1  NP_039602.1  0.24      0.40      
[00:40:55] INFO - Building clustermap.js visualisation
[00:40:55] INFO - Writing to: CTX.gbk
[00:40:55] INFO - Done!
(clinker) d@d:~/Documents/Investigaciones/paper2IMSAR/phages$

**Comment by davidmadariaga** [comment]
this is what i got on the terminal:

(clinker) d@d:~/Documents/Investigaciones/paper2IMSAR/phages$ clinker --dont_set_origin -i 0.2 --plot *.gbk
[00:45:10] INFO - Starting clinker
[00:45:10] INFO - Parsing files:
[00:45:10] INFO -   IMSAR-11_1copy.gbk
[00:45:10] INFO -   m13.gbk
[00:45:10] INFO -   mda.gbk
[00:45:10] INFO -   Ngo6.gbk
/home/d/anaconda3/envs/clinker/lib/python3.12/site-packages/Bio/Seq.py:2879: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
[00:45:10] INFO -   pf1.gbk
[00:45:10] INFO - Starting cluster alignments
[00:45:11] INFO - IMSAR-11_1copy vs m13
[00:45:11] INFO - IMSAR-11_1copy vs mda
[00:45:11] INFO - IMSAR-11_1copy vs Ngo6
[00:45:11] INFO - IMSAR-11_1copy vs pf1
[00:45:11] INFO - m13 vs mda
[00:45:11] INFO - m13 vs Ngo6
[00:45:11] INFO - m13 vs pf1
[00:45:11] INFO - mda vs Ngo6
[00:45:11] INFO - mda vs pf1
[00:45:11] INFO - Ngo6 vs pf1
[00:45:11] INFO - Generating results summary...
IMSAR-11_1copy vs m13
---------------------
Query                   Target       Identity  Similarity
gnl|Bakta|LMMBLF_04780  NP_510890.1  0.21      0.29      
gnl|Bakta|LMMBLF_04790  NP_510890.1  0.24      0.43      
gnl|Bakta|LMMBLF_04795  NP_510892.1  0.21      0.32      
gnl|Bakta|LMMBLF_04810  NP_510890.1  0.20      0.37      
gnl|Bakta|LMMBLF_04810  NP_510892.1  0.21      0.41      

IMSAR-11_1copy vs mda
---------------------
Query                   Target          Identity  Similarity
gnl|Bakta|LMMBLF_04775  WP_002223582.1  0.98      0.99      
gnl|Bakta|LMMBLF_04780  WP_002218477.1  0.98      0.98      
gnl|Bakta|LMMBLF_04780  WP_002223585.1  0.20      0.29      
gnl|Bakta|LMMBLF_04785  WP_002218476.1  1.00      1.00      
gnl|Bakta|LMMBLF_04790  WP_002218477.1  0.21      0.29      
gnl|Bakta|LMMBLF_04790  WP_002223585.1  1.00      1.00      
gnl|Bakta|LMMBLF_04790  WP_002216892.1  0.22      0.37      
gnl|Bakta|LMMBLF_04795  WP_002218476.1  0.21      0.32      
gnl|Bakta|LMMBLF_04795  WP_002223586.1  0.86      0.93      
gnl|Bakta|LMMBLF_04805  WP_042507217.1  0.84      0.87      
gnl|Bakta|LMMBLF_04810  WP_002223585.1  0.22      0.37      
gnl|Bakta|LMMBLF_04810  WP_002216892.1  1.00      1.00      
gnl|Bakta|LMMBLF_04815  WP_002212523.1  1.00      1.00      
gnl|Bakta|LMMBLF_04820  WP_002212521.1  1.00      1.00      

IMSAR-11_1copy vs Ngo6
----------------------
Query                   Target      Identity  Similarity
gnl|Bakta|LMMBLF_04775  AAW89813.2  0.46      0.59      
gnl|Bakta|LMMBLF_04780  AAW89810.1  0.21      0.29      
gnl|Bakta|LMMBLF_04780  AAW89812.1  0.63      0.74      
gnl|Bakta|LMMBLF_04785  AAW89809.1  0.20      0.34      
gnl|Bakta|LMMBLF_04785  AAW89811.1  0.58      0.81      
gnl|Bakta|LMMBLF_04785  AAW89815.1  0.24      0.33      
gnl|Bakta|LMMBLF_04790  AAW89810.1  0.25      0.56      
gnl|Bakta|LMMBLF_04790  AAW89815.1  0.23      0.39      
gnl|Bakta|LMMBLF_04795  AAW89809.1  0.30      0.48      
gnl|Bakta|LMMBLF_04795  AAW89811.1  0.22      0.37      
gnl|Bakta|LMMBLF_04795  AAW89812.1  0.20      0.36      
gnl|Bakta|LMMBLF_04795  AAW89815.1  0.22      0.35      
gnl|Bakta|LMMBLF_04800  AKO63689.1  0.21      0.34      
gnl|Bakta|LMMBLF_04800  AAW89808.2  0.47      0.63      
gnl|Bakta|LMMBLF_04805  AAW89807.1  0.63      0.72      
gnl|Bakta|LMMBLF_04810  AAW89806.1  0.34      0.47      
gnl|Bakta|LMMBLF_04810  AAW89810.1  0.20      0.37      
gnl|Bakta|LMMBLF_04810  AAW89815.1  0.22      0.40      
gnl|Bakta|LMMBLF_04815  AAW89805.1  0.37      0.49      
gnl|Bakta|LMMBLF_04820  AAW89804.1  0.43      0.59      

IMSAR-11_1copy vs pf1
---------------------
Query                   Target       Identity  Similarity
gnl|Bakta|LMMBLF_04780  NP_039600.1  0.20      0.30      
gnl|Bakta|LMMBLF_04780  NP_039603.1  0.21      0.32      
gnl|Bakta|LMMBLF_04790  NP_039602.1  0.21      0.28      
gnl|Bakta|LMMBLF_04790  NP_039603.1  0.24      0.45      
gnl|Bakta|LMMBLF_04810  NP_039602.1  0.22      0.35      
gnl|Bakta|LMMBLF_04810  NP_039603.1  0.21      0.40      

m13 vs mda
----------
Query        Target          Identity  Similarity
NP_510890.1  WP_002218477.1  0.21      0.29      
NP_510890.1  WP_002223585.1  0.24      0.43      
NP_510890.1  WP_002216892.1  0.20      0.37      
NP_510892.1  WP_002223586.1  0.21      0.34      
NP_510892.1  WP_002216892.1  0.21      0.41      

m13 vs Ngo6
-----------
Query        Target      Identity  Similarity
NP_510886.1  AAW89808.2  0.20      0.32      
NP_510886.1  AAW89809.1  0.21      0.27      
NP_510890.1  AAW89810.1  0.23      0.47      
NP_510890.1  AAW89815.1  0.20      0.38      
NP_510892.1  AAW89806.1  0.29      0.39      
NP_510892.1  AAW89812.1  0.21      0.34      

m13 vs pf1
----------
Query        Target       Identity  Similarity
NP_510887.1  NP_039602.1  0.23      0.39      
NP_510887.1  NP_039610.1  0.22      0.36      
NP_510887.1  NP_039613.1  0.21      0.30      
NP_510890.1  NP_039603.1  0.21      0.44      
NP_510891.1  NP_039604.1  0.21      0.28      
NP_510892.1  NP_039608.1  0.20      0.31      

mda vs Ngo6
-----------
Query           Target      Identity  Similarity
WP_002223582.1  AAW89813.2  0.46      0.61      
WP_002218477.1  AAW89810.1  0.21      0.29      
WP_002218477.1  AAW89812.1  0.62      0.74      
WP_002218476.1  AAW89809.1  0.20      0.34      
WP_002218476.1  AAW89811.1  0.58      0.81      
WP_002218476.1  AAW89815.1  0.24      0.33      
WP_002223585.1  AAW89810.1  0.25      0.56      
WP_002223585.1  AAW89815.1  0.23      0.39      
WP_002223586.1  AAW89809.1  0.30      0.47      
WP_002223586.1  AAW89811.1  0.21      0.32      
WP_002223586.1  AAW89812.1  0.22      0.38      
WP_002223586.1  AAW89815.1  0.24      0.35      
WP_042507217.1  AAW89807.1  0.60      0.69      
WP_002216892.1  AAW89806.1  0.34      0.47      
WP_002216892.1  AAW89810.1  0.20      0.37      
WP_002216892.1  AAW89815.1  0.22      0.40      
WP_002212523.1  AAW89805.1  0.37      0.49      
WP_002212521.1  AAW89804.1  0.43      0.59      

mda vs pf1
----------
Query           Target       Identity  Similarity
WP_002218477.1  NP_039603.1  0.21      0.32      
WP_002223585.1  NP_039602.1  0.21      0.28      
WP_002223585.1  NP_039603.1  0.24      0.45      
WP_002216892.1  NP_039602.1  0.22      0.35      
WP_002216892.1  NP_039603.1  0.21      0.40      

Ngo6 vs pf1
-----------
Query       Target       Identity  Similarity
AKO63689.1  NP_039608.1  0.22      0.38      
AAW89806.1  NP_039602.1  0.22      0.38      
AAW89806.1  NP_039605.1  0.22      0.35      
AAW89809.1  NP_039608.1  0.25      0.31      
AAW89809.1  NP_039613.1  0.21      0.29      
AAW89810.1  NP_039602.1  0.22      0.40      
AAW89810.1  NP_039603.1  0.28      0.47      
AAW89812.1  NP_039603.1  0.21      0.27      
AAW89815.1  NP_039602.1  0.24      0.40      
[00:45:11] INFO - Building clustermap.js visualisation
[00:45:11] INFO - Writing to: CTX.gbk
[00:45:11] INFO - Done!

**Comment by davidmadariaga** [comment]
I KNOW WHAT WAS WRONG (IT WAS ME) THAAAAAAAAAAAAAAAAANKSSSSSSSSSSSSSS THANKS THANKS THANKS
