### ISSUE TITLE
Possible to ignore coordinates and show gene order only?

### ISSUE THREAD

**Issue by RvV1979** [gamcil/clinker#17]
Thanks so much for what after some initial trialing seems to be a very useful tool! 
I am looking at plant genomic sequences that often have huge intergenic spaces due to accumulation of repetitive elements. Thus, genes appear rather sparsely in some parts of my plots. 

![clinker](https://user-images.githubusercontent.com/9930371/100201765-b948e600-2f00-11eb-954e-8e686ad685b9.png)

Would it be possible to ignore coordinates and show the ordering of genes only? (e.g. by setting scale to 0)
Or maybe I have missed such an option in the documentation?

Thanks

**Comment by cslamo** [comment]
I second this, and I'd add the possibility of automatic reorientation of sequences in which a gene of reference is inverted

**Comment by gamcil** [comment]
I like this idea but I'll have to have a think about the best way to implement it.

@RvV1979 By scale=0, do you mean genes themselves have no scale, or just that they are drawn immediately adjacent to each other (no intergenic gaps)?

@cslamo not sure I get what you mean - you want to specify a reference gene at the start and have clinker automatically reorient loci based on that gene? Or do that when you click to center the figure on a gene?

**Comment by RvV1979** [comment]
Thanks for your response. Given that plant genomes may expand in both intergenic spaces and in introns I think the best solution is to have no scale for the genes nor and their intergenic gaps. Thus, only showing the ordering and orientation of genes. Below is an example image of a recent paper that I generated "manually". 
![F7 large](https://user-images.githubusercontent.com/9930371/100851321-4f42ba80-3485-11eb-977b-da22a8379eed.jpg)
I am sure many of my colleagues and students would use clinker if it had this functionality. 

My suggestion about scale = 0 was just as a means to use an existing parameter. But I perhaps a separate toggle for removing scale of genes and their locations would be better.

**Comment by gamcil** [comment]
Ahh, cool figure. I think the separate toggles is a good idea, then enabling both should achieve the behaviour you're looking for. Should be easy enough to implement but I just need to find some time, I'll update this issue when I do.

**Comment by cslamo** [comment]
@gamcil what I mean is, often one or a few sequences are in the wrong direction (i.e., opposite to the majority). I suggest a button or check next to each sequence in case one wants to reverse-complement a sequence. 
I concur with @RvV1979 on the scaling issue. I have ~1Mbp and ~100Kbp spans in a given bunch of sequences.

**Comment by gamcil** [comment]
@RvV1979 I've added the ability to unscale genes/hide gaps with clinker v0.0.10, which can be installed now from pip.

@cslamo Do you mean in a way that isn't achieved by double clicking a locus? I've also added the ability to automatically flip loci when anchoring on a gene through the right click menu with v0.0.10 if that helps (#25).

**Comment by RvV1979** [comment]
@gamcil I have been testing the new version and it works near-excellently. 

I can also confirm that flipping a locus by right-clicking works. Thanks for implementing this so quickly!
