### ISSUE TITLE
pip3 install clinker instead pip install - Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by JuanMartinezV** [gamcil/clinker#19]
Hello, just an advice (because I had this "problem")

The last step of the instructions to install clinker says 

`pip install`

however you should type instead (if you are using Ubuntu 20.04 LTS and the output says that _pip was not found_)

`pip3 install clinker`

I'm kind of new in Linux so if someone had this issue I hope this can help 

- Juan

**Comment by gamcil** [comment]
Ah thanks for pointing that out, my system pip defaults to pip3 so I completely missed this. I'll add a note in the README.
