### ISSUE TITLE
pip install clinker -  ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by mafeeney** [gamcil/clinker#20]
Hello,

I tried using pip install clinker as described in the installation instructions - but had a long error message, ending with: 

ERROR: Command errored out with exit status 1: 'c:\users\trb18198\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\trb18198\\AppData\\Local\\Temp\\pip-install-_rw5tr0s\\biopython\\setup.py'"'"'; __file__='"'"'C:\\Users\\trb18198\\AppData\\Local\\Temp\\pip-install-_rw5tr0s\\biopython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\trb18198\AppData\Local\Temp\pip-record-oxf1pagw\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\trb18198\appdata\local\programs\python\python39\Include\biopython' Check the logs for full command output.

This bit is highlighted in white in the error message (so it may be important?) 
 ERROR: Failed building wheel for biopython
  Running setup.py clean for biopython
Failed to build biopython
Installing collected packages: biopython, clinker
    Running setup.py install for biopython ... error

I am not quite sure what I've done wrong....?

**Comment by mafeeney** [comment]
Managed to solve the problem by getting conda to install biopython (instead of letting pip manage it) - still baffled as to why this should be the case, but at least it's worked now!

**Comment by gamcil** [comment]
Glad you got it sorted! I've heard some people have had issues with installing biopython, but that's a weird one.
