### ISSUE TITLE
Feature request: match gene order

### ISSUE THREAD

**Issue by alexweisberg** [gamcil/clinker#25]
Hi,
The recent updates to clinker are great. The javascript GUI is a little slow when I have ~60 samples of 5 or 6 genes each, so flipping the orientation of each gene fragment takes a while. It would be nice to have an option to pick a gene as a reference, and flip the orientation of all other strains contigs with that gene to match the orientation. Right now its just based on the gene orientation from each original genome. Alternatively, an option to minimize inversions would be cool, basically flipping contigs so that there are as few "twists" in the final output as possible.

**Comment by gamcil** [comment]
Ah good idea, will try to add this for the next release. Maybe just left click to center like it is now, but this option in the right click menu? The second part will take a little more thinking.

**Comment by gamcil** [comment]
Added in clinker v0.0.10

**Comment by osuchanglab** [comment]
Great thank you!

**Comment by alexweisberg** [comment]
This is great! Thank you for adding it.

**Comment by sbthandras** [comment]
How do you use this feature?
