### ISSUE TITLE
Issue with anaconda3 on mac and Clinker

### ISSUE THREAD

**Issue by lgannon248** [gamcil/clinker#28]
Hi,

Clinker looks fantastic but I'm having trouble getting it going. I'm using a mac, I used pip to install Clinker:

$ pip install Clinker
Requirement already satisfied: Clinker in /anaconda3/lib/python3.7/site-packages (0.0.4)
Requirement already satisfied: numpy in /anaconda3/lib/python3.7/site-packages (from Clinker) (1.15.1)
Requirement already satisfied: scipy in /anaconda3/lib/python3.7/site-packages (from Clinker) (1.1.0)
Requirement already satisfied: biopython in /anaconda3/lib/python3.7/site-packages (from Clinker) (1.73)

but calling Clinker leads to a confusing error message:

$ Clinker
Traceback (most recent call last):
  File "/anaconda3/bin/Clinker", line 6, in <module>
    from clinker.main import main
  File "/anaconda3/lib/python3.7/site-packages/clinker/main.py", line 14, in <module>
    from clinker import align
  File "/anaconda3/lib/python3.7/site-packages/clinker/align.py", line 20, in <module>
    from Bio.Align import substitution_matrices
ImportError: cannot import name 'substitution_matrices' from 'Bio.Align' (/anaconda3/lib/python3.7/site-packages/Bio/Align/__init__.py)

Edit: I can now go to /anaconda3/lib/python3.7/site-packages/Bio/Align/__init__.py and see this file, can't find any "substitution_matrices" string in this text file.

Any help much appreciated.

**Comment by gamcil** [comment]
I think this might just be a problem with an older version of BioPython - you have version 1.73, but the substition_matrices part was added to that module in version 1.75. I think just doing `conda update biopython` should fix this issue.

**Comment by lgannon248** [comment]
Thank you for putting me on the right track! 
`$ conda update biopython` wasn't working for unknown reason, but `$ pip install biopython --upgrade` did work in the end and now clinker can run. Thankyou!

**Comment by gamcil** [comment]
Glad you got it working 👍
