### ISSUE TITLE
Bioconda submission naming

### ISSUE THREAD

**Issue by rpetit3** [gamcil/clinker#29]
Hello!

I'm going to submit a recipe to Bioconda, but there is already a recipe for another tool called Clinker (https://anaconda.org/bioconda/clinker).

Do you have a preferred alternative name for the bioconda recipe (e.g. clinker-py, clinker-fig, python-clinker)

Thank you!
Robert

**Comment by gamcil** [comment]
Ah cool. No real preference, I'd be happy with clinker-py.

**Comment by rpetit3** [comment]
clinker is now available on Bioconda under the name clinker-py (https://bioconda.github.io/recipes/clinker-py/README.html)

Really looking forward to testing it out! 

Going to go ahead and close this issue. Cheers
