### ISSUE TITLE
How to adjust the distance between the sample name and the sequence in clinker?

### ISSUE THREAD

**Issue by jeep3** [gamcil/clinker#30]
Hello, I want to ask a question. How to adjust the distance between the sample name and the sequence in clinker? There is a big gap in the middle. As shown below:
![image](https://user-images.githubusercontent.com/28469054/102644048-76c1a480-4160-11eb-983e-36ad5fe3f09e.png)

**Comment by gamcil** [comment]
Hey, if you hover over each cluster you should be able to drag the black box to the first gene. That will automatically reposition the label to be closer to the genes.

**Comment by jeep3** [comment]
Thanks. It goes back to the first gene according to your method.
