### ISSUE TITLE
Addition to help text: Double click flips contig

### ISSUE THREAD

**Issue by passdan** [gamcil/clinker#33]
One thing that I thought was missing so bad that I was going to raise an issue is that you can't flip contigs in the plot! Except you can! However it's not in any of the manual, wiki, or instructions in the html help box.

Suggestion: Add the line:
"To flip orientation of contig double click"

**Comment by gamcil** [comment]
Didn't realise I hadn't already added this! Thanks for the note, explains why a bunch of people haven't realised they can flip contig orientation. Added a little note in ad6f1b539a342b124324a38a34e3eff3013a3f43 which should land in the next release, whenever that comes.

**Comment by passdan** [comment]
Yeah! Probably such an obvious one for you that it totally escaped! Great tool by the way :-)
