### ISSUE TITLE
"This SVG is not valid, validate it before opening"

### ISSUE THREAD

**Issue by kforcone** [gamcil/clinker#45]
Hi, 

I was able to successfully create a clinker html and edit it in the web interface. I clicked the 'save as an svg' button to do so, however any application that I try to open it with, including Adobe Illustrator 2021 and Inkscape gives me the message 'This SVG is not valid, validate it before opening'.

 I tried AI and Inkscape on different computers with the same error. Web validators such as W3C markup do not detect a problem with the SVG either. Has this issue arisen before? 

Is there any way to fix it or to save in another format such as pdf? I have attached the SVG as a TXT file below for reference.

Thanks,

Kathryn

SVG as a text file
[clinker_test.txt](https://github.com/gamcil/clinker/files/5907500/clinker_test.txt)

**Comment by gamcil** [comment]
I think I found the issue - if you change the xmlns="http://www.w3.org/2000/node" to xmlns="http://www.w3.org/2000/svg" in your SVG, the file opens fine in Inkscape for me (can't test Illustrator, but should work?). I think this must have been a rogue find and replace bug from me... I've uploaded a new version of clinker (v0.0.14) which should fix this, so try updating and see if it works.

**Comment by kforcone** [comment]
Hi @gamcil, clinker v0.0.14 worked perfectly, I was able to open the html, save as an svg and open in Illustrator:) Thanks!!
