### ISSUE TITLE
Changing color of a gene to a specific desired color

### ISSUE THREAD

**Issue by Cereben** [gamcil/clinker#46]
Really enjoying the clinker tool, but was wondering if there was a way to manually change the color of a particular gene in the cluster to a color of my choosing. For instance, if I have a cluster with 5 p450s, it often colors some in one color and others in another color, but it doesn't seem that I can manually change them to display as the same color. Is there a feature for this in the current version of clinker?

**Comment by gamcil** [comment]
At the moment no, you'd have to do this after saving the SVG in e.g. Inkscape. But I'll add this feature for the next release when I get some time.

**Comment by tyleralsup** [comment]
Ok. Thanks!

**Comment by rob2go** [comment]
Also should be nice to have an option to take out the outline of the arrows, keeping only the filling color.

**Comment by gamcil** [comment]
As of clinker v0.0.17 (just released), you can now change individual gene colours through the tooltip, as well as change gene arrow stroke colour/width (set width=0 to hide completely).
