### ISSUE TITLE
RecursionError in `clinker.align.consolidate` (and a proposed fix)

### ISSUE THREAD

**Issue by althonos** [gamcil/clinker#49]
Hi again @gamcil ,

I used `clinker` to align 60 clusters, each of them sharing between 1 and 4 homolog protein. This caused `clinker.align.consolidate` to throw a `RecursionError`, as it seemed to have some issues merging everything.

As you pointed in the documentation, you used the Rosetta stone recursive implementation; there is an iterative implementation that would likely fix that issue. However, there is an algorithmic data structure that would work better for the kind of task that `GlobalAligner.build_gene_groups` is trying to achieve: a [disjoint-set](https://en.wikipedia.org/wiki/Disjoint-set_data_structure). 

If you are fine adding an external pure-Python dependency ([`disjoint-set`](https://pypi.org/project/disjoint-set/), here is the replacement code:
```python
class GlobalAligner:

    # ...

    def build_gene_groups(self):
        """Builds gene groups based on currently stored gene-gene links."""

        ds = disjoint_set.DisjointSet()
        for link in self._links.values():
            ds.union(link.query.uid, link.target.uid)

        for genes in ds.itersets():
            group = Group(label=f"Group {len(self.groups)}", genes=list(genes))
            self.groups.append(group)
```

**Comment by althonos** [comment]
... I literally read #48 five minutes after opening this issue :sweat_smile:

**Comment by gamcil** [comment]
Haha yeah I just swapped it out for the iterative version but the disjoint set idea might still be better. I'd probably still welcome a PR for this, with your above code and the added dependency in `setup.py`
