### ISSUE TITLE
Running Clinker on a Server?

### ISSUE THREAD

**Issue by Robaina** [gamcil/clinker#60]
Hi all! Just came across Clinker, great tool @gamcil! I was considering using Clinker in my classes, would be cool to run Clinker directly in my server so students didn't have to install it locally. I'm not an expert in web developing but know a bit so I considered to give it a go.

Any suggestions on how would you do it? 

Thanks!
Semidán

**Comment by gamcil** [comment]
Hi @Robaina, sorry it took me so long to get back to this, must have forgotten to answer.

Do you mean you want to develop a GUI frontend for clinker on your server? I don't have a lot of experience in that area, but I think the easiest way would just be a simple Flask application with a page to pick files and change the settings, then have a run button linked to a Flask route which calls clinker with those files/settings either using `clinker()` in `main.py` or as a subprocess (i.e. install on your server, then `subprocess.run(['clinker' 'file1.gbk', 'file2.gbk', 'file3.gbk', '-p', 'plot.html'])`. Then you would just have to load the generated HTML file using Flask.

**Comment by Robaina** [comment]
Hi @gamcil, no worries. Thanks for the reply. I had actually forgotten about this question. I solved the problem through PHP and some changes in Clinker's code. Works like a charm!

**Comment by gamcil** [comment]
Awesome, glad you got it working :)
