### ISSUE TITLE
Elaborate on the input file contents

### ISSUE THREAD

**Issue by multimeric** [gamcil/clinker#65]
Hi, I'm trying to integrate clinker into a pipeline I'm working on. However I'm confused about a few things:

* Should the input genbank files contain protein or DNA sequences?
* Do we provide the entire gene cluster as a single sequence, and the entire file contains multiple clusters; or do we provide each gene as a single sequence, meaning that each file contains a single cluster?
* If the entire cluster is a single sequence, how do you determine the position of the genes within that sequence?

**Comment by multimeric** [comment]
This function makes me think that each genbank file is a cluster, and each sequence within that file is a gene: https://github.com/gamcil/clinker/blob/10c7a1da6a30cf7b93d28f67474c9a34f098b61d/clinker/classes.py#L201

**Comment by gamcil** [comment]
Hey, 
* clinker expects multiple GenBank files, each corresponding to a different cluster. Each file should contain nucleotide sequence for a region, as well as sequence feature annotations for that region (feature types, start position, end position etc).
* clinker will try to parse the protein translations from CDS sequence features, and if those aren't in there, manually translate from the nucleotide sequence. 
* Gene positions are taken directly from the sequence features; clinker will try to match a CDS feature with its corresponding gene feature to get the correct coordinates (no UTRs etc), but failing that will use the coordinates of the coding sequence.
* If a GenBank file contains more than one sequence record, clinker still recognises the file as a single cluster, but each record would be a separate locus (drawn separately but on the same row).

The ``examples`` folder has some good examples of valid input. Hope that helps!

**Comment by multimeric** [comment]
Great, thanks! And just to clarify, I assume that means that the genbank files have to be nucleotide sequences, not protein sequences (the GenPept format)? The reason I ask these questions that don't normally matter is because I'm not using genbank itself as the source of my annotations. Rather I'm having to create these files from another data source, which is why I'm after the specifics.

**Comment by gamcil** [comment]
Yeah you're right, nucleotide GenBank, not GenPept, since we want to display the genomic region the genes are on. Though, you don't necessarily need nucleotide sequence if your CDS sequence features all have protein translations in them, as long as the overall GenBank format is still valid (I think some other pipelines generate files like that).
