### ISSUE TITLE
clustermap loading slow

### ISSUE THREAD

**Issue by yzjie6** [gamcil/clinker#87]
I try to clinker 37 gene cluster but it runs super slow in chrome browser, I also tried different browsers and different computers, it is impossible to edit now, do you have some suggestions about it? Thanks

**Comment by gamcil** [comment]
Hi @yzjie6, unfortunately there isn't a lot that can be done about this. The visualisation is essentially a big SVG file with a lot of elements which can get slow (especially when you have a lot of clusters). Possibly you could trim your input files before giving them to clinker (if you have extra sequence features up/downstream of the cluster), or split up your analysis into batches and combine the images afterwards (e.g. in InkScape)?
