### ISSUE TITLE
Conda package errors

### ISSUE THREAD

**Issue by Anto007** [gamcil/clinker#91]
Just for the sake of clinker users who might have experienced issues like me- conda installation of clinker was giving me a lot of python errors (for e.g.,` too many values to unpack`) even when testing with the example .gbk files as input. The pip installed version works fine without errors at my end (on Python 3.7.10; Ubuntu 20.04.2 LTS). Hope this helps somebody!

**Comment by jacekzkominek** [comment]
I am actually encountering this problem right now, and unfortunately neither the Conda nor PIP versions are working. I even went back a few versions, and it's still the same error - "ValueError: too many values to unpack". Maybe it's one of the dependencies that is causing this? I am running this on MacOS 13.0.1.

**Comment by gamcil** [comment]
Thanks for picking this up. Looks like clinker was a casualty of this change in v1.80 https://github.com/biopython/biopython/issues/4183. I've just released version 0.0.26 of clinker (should be on PyPI shortly) which should fix the issue for pre/post 1.80.

**Comment by jacekzkominek** [comment]
Lovely, glad you were able to track it down, and thanks for the fix!
