### ISSUE TITLE
Can't save changes to session

### ISSUE THREAD

**Issue by camilo-monge** [gamcil/clinker#93]
Hello and thank you for your wonderful tool.

I have been using clinker for a while now, usually on the cagecat server. Since it has been down for the last weeks I've been trying to use it locally (installed in ubuntu via pip), however, I haven't been able to save/ reload any changes in my session. 

I am running it as
`clinker *.gbff -p clinker.html -s session.json`
and everything works fine, but when I try to reload later with either
`clinker -p clinker.html -s session.json`
or
`clinker *.gbff -s session.json`
An error tells me that files are needed, and if I add them by running 
`clinker *.gbff -p clinker.html -s session.json` 
the program runs the alignments again and the changes made in my previous session are not reflected. I remember that the cagecat server had a " save session state" or similar which I cannot find in the local version. How can I save session state locally? 

Thanks for the help.

**Comment by gamcil** [comment]
Hey @camilo-monge, thanks for the report. This is definitely a bug - clinker currently throws an error if no file paths are provided before it checks for a session file. I will fix this in the next release. 

As for the session state, the visualisation part of clinker has a 'Save data' button for saving the state of the visualisation (configuration for the plot + plot data) which is different to the session file produced on the command line. That will allow you to save/load a visualisation directly in the browser. At the moment there isn't a direct way to open a blank clinker visualisation, so you would have to e.g. run clinker on some example files with `-p`, then load your saved JSON with the 'Choose file' button in the right hand side menu.

**Comment by camilo-monge** [comment]
Hey @gamcil thanks for the guidance. Apparently the issues I was having were due to installing with pip, which gives ver 0.0.7, which does not allow to save session changes. I installed the conda version and works like a charm. Wonder why that happened, since I cloned just as explained in the github about two weeks ago.

Happy holidays!
