### ISSUE TITLE
the legend

### ISSUE THREAD

**Issue by Oelsakha** [gamcil/clinker#95]
Hi all 
thank you for nice tool, it works great. however is there is any way to name the legend automatically because I have 41 gene and the colors are very near and so confusing.

**Comment by gamcil** [comment]
Hey @Oelsakha, not within the visualisation itself unfortunately. The closest way would be to use the ``--gene-functions`` table (shown here: https://github.com/gamcil/clinker#defining-gene-groups-by-function). This would allow you to create groups manually in a text file which are then used in the visualisation.

**Comment by Oelsakha** [comment]
That is great, it reduces the legend so much and makes it more organized. 
But I have a new problem==> the clusters are duplicated in plots
I can say I have 3 clusters and it give me 6 groups.

**Comment by Oelsakha** [comment]
<img width="209" alt="Screenshot 2023-01-09 at 5 31 42 AM" src="https://user-images.githubusercontent.com/77561007/211288524-bb7dc7ca-1587-4f7a-b5e1-64e59d50ae18.png">

**Comment by Oelsakha** [comment]
Never mind for the plot problem it solved. 
Thank you again for your help.
